


function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from neoParams.py


var __name__ = '__main__';


COLORS=['SILVER','PINK','PURPLE','WHITE','BLACK','ORANGE','GREEN','BLUE','GREY','BROWN','YELLOW','GOLD','BEIGE','RED'];

COLORS_MAP={};


container_py2js_1=COLORS;
var generator_py2js_2 = new Generator(container_py2js_1);
for(cl=generator_py2js_2.nextValue();generator_py2js_2.hadMore();cl=generator_py2js_2.nextValue()) {
    
    (COLORS_MAP[cl])=[cl];
}

(COLORS_MAP['NONE'])=[];

PATTERNS_MAP={'GEOMETRIC':['STRIPE','PRINT'],'LEOPARD':['LEOPARD','PRINT','ANIAML'],'FLORAL':['FLORAL','PRINT'],'TWO COLOR':['TWO COLOR'],'STRIPE':['STRIPE'],'DOT':['DOT'],'SCATCH':['STRIPE','PRINT'],'PLAID':['PLAID'],'PLAIN':[],'NONE':[]};

MATERIALS_MAP={'JEANS':['JEANS'],'LACE':['LACE'],'LEATHER':['LEATHER'],'NONE':[]};

SLEEVES_MAP={'SLEEVELESS':['SLEEVELESS','CAP-SLEEVE'],'STRAP':['STRAP'],'SHORT-SLEEVE':['SHORT-SLEEVE','CAP-SLEEVE'],'THIRD_QUARTER':['3/4-SLEEVE'],'STRAPLESS':['STRAPLESS'],'HALTER':['HALTER-NECK'],'LONG-SLEEVE':['LONG-SLEEVE'],'ASYMMETRIC-SLEEVE':['ONE-SHOULDER','ASYMMETRIC-SLEEVE'],'NONE':[]};

LENGTH_MAP={'SHORT':['SHORT','MINI'],'MIDI':['MIDI'],'LONG':['LONG','MAXI'],'NONE':[]};

NECK_MAP={'CLOSED':['BOAT-NECK','ROUND-NECK','BARDOT-NECK'],'HEART':['SIMPLE-NECK','HEART-NECK'],'V':['V-NECK'],'BUTTONED':['SHIRT-DRESS'],'GOLF':['HIGH-NECK','TURTLENECK'],'SQUARE':['SQUARE-NECK'],'COLLAR':['COLLAR'],'WRAP':['WRAP-NECK'],'WIDE':['SIMPLE-NECK','WIDE-NECK'],'FALLING':[],'NONE':[]};

MISC_MAP={'TRANSPARENT':['TRANSPARENT'],'STUD':['STUD'],'POCKET':['POCKET'],'BELT':['BELT'],'PLEAT':['PLEAT'],'NONE':[]};

CAT_MAP={'Color':COLORS_MAP,'Pattern':PATTERNS_MAP,'Material':MATERIALS_MAP,'Sleeve':SLEEVES_MAP,'Length':LENGTH_MAP,'Neck':NECK_MAP,'Misc':MISC_MAP};


exports.QUESTIONS_VAL = {"Color" : COLORS_MAP, "Pattern" : PATTERNS_MAP, "Material" : MATERIALS_MAP, "Sleeve" : SLEEVES_MAP, "Length" : LENGTH_MAP,"Neck" : NECK_MAP, "Misc" : MISC_MAP}

exports.QUESTIONS = { "Color" : "What color is the dress?",
					 "Pattern" : "What is the pattern of the dress?", 
					 "Material" : "What is the material of the dress?",
					 "Sleeve" : "What kind of sleeves the dress has?",
					 "Length" : "What is the length of the dress?",
					 "Neck" : "what kind of neck the dress has?",
					  "Misc" : "Any other properties of the dress?"}
					  
exports.QUESTIONS_ORDER = ["Color", "Pattern",  "Neck", "Sleeve","Material",  "Misc", "Length"] 				  
exports.RELATIONS={"Color" : 'ITEM_COLOR', "Pattern": 'ITEM_PATTERN',  "Neck" :'ITEM_NECK' , "Sleeve" : 'ITEM_SLEEVE',"Material" : 'ITEM_MATERIAL',  "Misc" : 'ITEM_MISC', "Length" :'ITEM_LENGTH' }
 
imgPrefix = 'http://donde-app.com:2222/0.1/API/getImg/323232/img='
exports.IMAGES = {}
for (q in this.QUESTIONS_ORDER){
	cat = this.QUESTIONS_ORDER[q]
	this.IMAGES[cat] = {}
	s="["
	for (val in this.QUESTIONS_VAL[cat]){
	    for (in_val in this.QUESTIONS_VAL[cat][val])
	       s+=" "+this.QUESTIONS_VAL[cat][val][in_val]
		this.IMAGES[cat][val] = imgPrefix + val
		if (cat == "Material")
			this.IMAGES[cat][val] = ""
		if (cat == "Misc")
			this.IMAGES[cat][val] = ""	
			
	}
	s+="]"
	//console.log(s);
	//console.log(this.IMAGES[cat])
}

 

